### ISSUE TITLE
make less thing that $LINES is 8 shorter than it is, or something, so it doesn't auto-quit

### ISSUE THREAD

**Issue by brewneaux** [brewneaux/mycli#3]

**Comment by amjith** [comment]
No need to mess with $LINES. I'm manipulating $LESS env var to set options to the less command. 

https://github.com/dbcli/mycli/blob/master/mycli/main.py#L446

One of the options is -F which does this: 

```
-F or --quit-if-one-screen
Causes less to automatically exit if the entire file can be displayed on the first screen.
```

So you can just take out the -F from that based on a config or with the latest version of mycli you can actually set a pager variable in your ~/.my.cnf file. 

eg: 

```
pager = 'less -SXR' 
```

And that will be used instead of using the defaults.

**Comment by brewneaux** [comment]
Oh good call. I didn't think about that - and messing with $LINES will actually mess up more than it will fix. Closing.
